// <auto-generated />
using System;
using FinanceTracking.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanceTracking.API.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    partial class FinanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceTracking.API.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FinanceTracking.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color_hex");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_categories_group_id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("FinanceTracking.API.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsPersonal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_personal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_groups_owner_id");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("FinanceTracking.API.Models.GroupMember", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_date");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("UserId", "GroupId")
                        .HasName("pk_group_members");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_group_members_group_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_group_members_role_id");

                    b.ToTable("group_members", (string)null);
                });

            modelBuilder.Entity("FinanceTracking.API.Models.GroupMemberHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<bool?>("ActiveAfter")
                        .HasColumnType("boolean")
                        .HasColumnName("active_after");

                    b.Property<bool?>("ActiveBefore")
                        .HasColumnType("boolean")
                        .HasColumnName("active_before");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int?>("RoleIdAfter")
                        .HasColumnType("integer")
                        .HasColumnName("role_id_after");

                    b.Property<int?>("RoleIdBefore")
                        .HasColumnType("integer")
                        .HasColumnName("role_id_before");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id", "GroupId")
                        .HasName("pk_group_member_histories");

                    b.HasIndex("ChangedByUserId")
                        .HasDatabaseName("ix_group_member_histories_changed_by_user_id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_group_member_histories_group_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_group_member_histories_user_id");

                    b.ToTable("group_member_histories", (string)null);
                });

            modelBuilder.Entity("FinanceTracking.API.Models.ProductData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id", "GroupId")
                        .HasName("pk_product_data");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_product_data_group_id");

                    b.ToTable("product_data", (string)null);
                });

            modelBuilder.Entity("FinanceTracking.API.Models.ProductDataCategory", b =>
                {
                    b.Property<int>("ProductDataId")
                        .HasColumnType("integer")
                        .HasColumnName("product_data_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.HasKey("ProductDataId", "CategoryId", "GroupId")
                        .HasName("pk_product_data_categories");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_product_data_categories_category_id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_product_data_categories_group_id");

                    b.HasIndex("ProductDataId", "GroupId")
                        .HasDatabaseName("ix_product_data_categories_product_data_id_group_id");

                    b.ToTable("product_data_categories", (string)null);
                });

            modelBuilder.Entity("FinanceTracking.API.Models.ProductEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<int>("ProductDataId")
                        .HasColumnType("integer")
                        .HasColumnName("product_data_id");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<int>("ReceiptId")
                        .HasColumnType("integer")
                        .HasColumnName("receipt_id");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id", "GroupId")
                        .HasName("pk_product_entries");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_product_entries_group_id");

                    b.HasIndex("ProductDataId", "GroupId")
                        .HasDatabaseName("ix_product_entries_product_data_id_group_id");

                    b.HasIndex("ReceiptId", "GroupId")
                        .HasDatabaseName("ix_product_entries_receipt_id_group_id");

                    b.ToTable("product_entries", (string)null);
                });

            modelBuilder.Entity("FinanceTracking.API.Models.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_file_name");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_date");

                    b.Property<int?>("SellerId")
                        .HasColumnType("integer")
                        .HasColumnName("seller_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_type");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id", "GroupId")
                        .HasName("pk_receipts");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_receipts_created_by_user_id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_receipts_group_id");

                    b.HasIndex("SellerId", "GroupId")
                        .HasDatabaseName("ix_receipts_seller_id_group_id");

                    b.ToTable("receipts", (string)null);
                });

            modelBuilder.Entity("FinanceTracking.API.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("FinanceTracking.API.Models.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id", "GroupId")
                        .HasName("pk_sellers");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_sellers_group_id");

                    b.ToTable("sellers", (string)null);
                });

            modelBuilder.Entity("FinanceTracking.API.Models.Category", b =>
                {
                    b.HasOne("FinanceTracking.API.Models.Group", "Group")
                        .WithMany("Categories")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_categories_groups_group_id");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("FinanceTracking.API.Models.Group", b =>
                {
                    b.HasOne("FinanceTracking.API.Models.AppUser", "Owner")
                        .WithMany("OwnedGroups")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_groups_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("FinanceTracking.API.Models.GroupMember", b =>
                {
                    b.HasOne("FinanceTracking.API.Models.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_members_groups_group_id");

                    b.HasOne("FinanceTracking.API.Models.Role", "Role")
                        .WithMany("GroupMembers")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_group_members_roles_role_id");

                    b.HasOne("FinanceTracking.API.Models.AppUser", "User")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_members_users_user_id");

                    b.Navigation("Group");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceTracking.API.Models.GroupMemberHistory", b =>
                {
                    b.HasOne("FinanceTracking.API.Models.AppUser", "ChangedByUser")
                        .WithMany("HistoryChangesMade")
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_group_member_histories_users_changed_by_user_id");

                    b.HasOne("FinanceTracking.API.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_member_histories_groups_group_id");

                    b.HasOne("FinanceTracking.API.Models.AppUser", "User")
                        .WithMany("HistoryActions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_group_member_histories_users_user_id");

                    b.Navigation("ChangedByUser");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceTracking.API.Models.ProductData", b =>
                {
                    b.HasOne("FinanceTracking.API.Models.Group", "Group")
                        .WithMany("Products")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_data_groups_group_id");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("FinanceTracking.API.Models.ProductDataCategory", b =>
                {
                    b.HasOne("FinanceTracking.API.Models.Category", "Category")
                        .WithMany("ProductDataCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_data_categories_categories_category_id");

                    b.HasOne("FinanceTracking.API.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_data_categories_groups_group_id");

                    b.HasOne("FinanceTracking.API.Models.ProductData", "ProductData")
                        .WithMany("ProductDataCategories")
                        .HasForeignKey("ProductDataId", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_data_categories_product_data_product_data_id_group_");

                    b.Navigation("Category");

                    b.Navigation("Group");

                    b.Navigation("ProductData");
                });

            modelBuilder.Entity("FinanceTracking.API.Models.ProductEntry", b =>
                {
                    b.HasOne("FinanceTracking.API.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_entries_groups_group_id");

                    b.HasOne("FinanceTracking.API.Models.ProductData", "ProductData")
                        .WithMany("ProductEntries")
                        .HasForeignKey("ProductDataId", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_entries_product_data_product_data_id_group_id");

                    b.HasOne("FinanceTracking.API.Models.Receipt", "Receipt")
                        .WithMany("ProductEntries")
                        .HasForeignKey("ReceiptId", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_entries_receipts_receipt_id_group_id");

                    b.Navigation("Group");

                    b.Navigation("ProductData");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("FinanceTracking.API.Models.Receipt", b =>
                {
                    b.HasOne("FinanceTracking.API.Models.AppUser", "CreatedByUser")
                        .WithMany("CreatedReceipts")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_receipts_users_created_by_user_id");

                    b.HasOne("FinanceTracking.API.Models.Group", "Group")
                        .WithMany("Receipts")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_receipts_groups_group_id");

                    b.HasOne("FinanceTracking.API.Models.Seller", "Seller")
                        .WithMany("Receipts")
                        .HasForeignKey("SellerId", "GroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_receipts_sellers_seller_id_group_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Group");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("FinanceTracking.API.Models.Seller", b =>
                {
                    b.HasOne("FinanceTracking.API.Models.Group", "Group")
                        .WithMany("Sellers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sellers_groups_group_id");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("FinanceTracking.API.Models.AppUser", b =>
                {
                    b.Navigation("CreatedReceipts");

                    b.Navigation("GroupMemberships");

                    b.Navigation("HistoryActions");

                    b.Navigation("HistoryChangesMade");

                    b.Navigation("OwnedGroups");
                });

            modelBuilder.Entity("FinanceTracking.API.Models.Category", b =>
                {
                    b.Navigation("ProductDataCategories");
                });

            modelBuilder.Entity("FinanceTracking.API.Models.Group", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Members");

                    b.Navigation("Products");

                    b.Navigation("Receipts");

                    b.Navigation("Sellers");
                });

            modelBuilder.Entity("FinanceTracking.API.Models.ProductData", b =>
                {
                    b.Navigation("ProductDataCategories");

                    b.Navigation("ProductEntries");
                });

            modelBuilder.Entity("FinanceTracking.API.Models.Receipt", b =>
                {
                    b.Navigation("ProductEntries");
                });

            modelBuilder.Entity("FinanceTracking.API.Models.Role", b =>
                {
                    b.Navigation("GroupMembers");
                });

            modelBuilder.Entity("FinanceTracking.API.Models.Seller", b =>
                {
                    b.Navigation("Receipts");
                });
#pragma warning restore 612, 618
        }
    }
}
